baseURL = "https://chenkai0520.github.io"
languageCode = "zh-cn"
title = "CK's Blog"
theme = "hugo-theme-coder"
paginate = 15
enableGitInfo = true


[params]
  hideFooter = true
  hideCredits = true
  hideCopyright = true
  colorScheme = "auto"
  hidecolorschemetoggle = false
  customSCSS = ["scss/custom.scss"]
  customJS = ["js/custom.js", "js/font.min.js"]
  editUrl = "https://github.com/chenkai0520/chenkai0520.github.io/edit/main"

[taxonomies]
  # category = "categories"
  tag = "tags"

# Menu links
[[menu.main]]
  name = "Home"
  weight = 1
  url  = "/"
# [[menu.main]]
#   name = "Categories"
#   weight = 2
#   url  = "categories/"
[[menu.main]]
  name = "Tags"
  weight = 3
  url  = "tags/"
[[menu.main]]
  name = "RSS"
  weight = 4
  url  = "/index.xml"
[[menu.main]]
  name = "About"
  weight = 5
  url = "about/"

[frontmatter]
  date = [ ":git", "lastmod" ]